// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

export const REQUEST_BOOKS_LIST = 'REQUEST_BOOKS_LIST';
export const SUCCESS_BOOKS_LIST = 'SUCCESS_BOOKS_LIST';
export const ERROR_BOOKS_LIST = 'ERROR_BOOKS_LIST';

export const REQUEST_BOOK_DETAIL = 'REQUEST_BOOK_DETAIL';
export const SUCCESS_BOOK_DETAIL = 'SUCCESS_BOOK_DETAIL';
export const ERROR_BOOK_DETAIL = 'ERROR_BOOK_DETAIL';

export const REQUEST_SAVE_BOOK = 'REQUEST_SAVE_BOOK';
export const SUCCESS_SAVE_BOOK = 'SUCCESS_SAVE_BOOK';
export const ERROR_SAVE_BOOK = 'ERROR_SAVE_BOOK';

export const REQUEST_DELETE_BOOK = 'REQUEST_DELETE_BOOK';
export const SUCCESS_DELETE_BOOK = 'SUCCESS_DELETE_BOOK';
export const ERROR_DELETE_BOOK = 'ERROR_DELETE_BOOK';

export const SET_FILTERS = 'SET_FILTERS';
export const SET_PAGE = 'SET_PAGE';
export const RESET_FILTERS = 'RESET_FILTERS';

export const REQUEST_AUTHORS_LIST = 'REQUEST_AUTHORS_LIST';
export const SUCCESS_AUTHORS_LIST = 'SUCCESS_AUTHORS_LIST';
export const ERROR_AUTHORS_LIST = 'ERROR_AUTHORS_LIST';

export const CLEAR_CURRENT_BOOK = 'CLEAR_CURRENT_BOOK';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';
export const ERROR_PROFILE = 'ERROR_PROFILE';